<a href="https://colab.research.google.com/github/kiranch97/Machine-Learning-Algorithms-for-Beginner-s/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Spam Mail Prediction**

In [3]:
# Load the Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
# Load the dataset

df = pd.read_csv('/content/spam_ham_dataset.csv')

In [5]:
df.head()

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5171 non-null   int64 
 1   label       5171 non-null   object
 2   text        5171 non-null   object
 3   label_num   5171 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 161.7+ KB


In [7]:
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [8]:
df.shape

(5171, 4)

In [9]:
df['label'].value_counts()

label
ham     3672
spam    1499
Name: count, dtype: int64

In [10]:
df['label'].replace({'ham':0,'spam':1},inplace=True)

In [11]:
df.head()

Unnamed: 0  label                                               text  \
0         605      0  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349      0  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624      0  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685      1  Subject: photoshop , windows , office . cheap ...   
4        2030      0  Subject: re : indian springs\r\nthis deal is t...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0

In [12]:
df.drop(['Unnamed: 0','label_num'],axis=1,inplace=True)

In [13]:
df.head()

label                                               text
0      0  Subject: enron methanol ; meter # : 988291\r\n...
1      0  Subject: hpl nom for january 9 , 2001\r\n( see...
2      0  Subject: neon retreat\r\nho ho ho , we ' re ar...
3      1  Subject: photoshop , windows , office . cheap ...
4      0  Subject: re : indian springs\r\nthis deal is t...

In [14]:
x = df['text']
y = df['label']

In [37]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=3)

In [16]:
X_train.shape, X_test.shape, Y_train.shape, Y_test

((4136,),
 (1035,),
 (4136,),
 1566    0
 1988    1
 1235    0
 2868    0
 4903    0
        ..
 1175    1
 4476    0
 4198    1
 2689    0
 2142    0
 Name: label, Length: 1035, dtype: int64)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names_out())
"""OUTPUT: array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)"""

['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


"OUTPUT: array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',\n       'this'], dtype=object)"

In [19]:
X.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [38]:
vectorizer = TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [39]:
new_X_train = vectorizer.fit_transform(X_train)
new_X_test = vectorizer.transform(X_test)

In [40]:
# Model Creation
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(new_X_train, Y_train)
lr_prediction = lr.predict(new_X_test)


In [41]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, lr_prediction)
print(accuracy)

0.9806763285024155


In [42]:
df_new =pd.read_csv('/content/emails.csv')

In [51]:
corpus = [
     'Check with your email provider to see whether it has enabled a spam filter for your account. ',
     'But one spam email this week really made me sit up. .',
     'Spam text messages can be forwarded on to your mobile provider for it to take action against persistent offenders. ',
     'He said computer users should lessen the risk by loading the free spam filters offered by most broadband suppliers. ',]

In [52]:
corpus_new = vectorizer.transform(corpus)

In [53]:
corpus_new.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
corpus_new.shape

(4, 45076)

In [55]:
corpus_new_Y_pred = lr.predict(corpus_new)

In [56]:
print(corpus_new_Y_pred)

[1 1 1 1]


In [50]:
print(corpus_new_Y_pred)

[1 1 1 1]
